// <auto-generated />
using System;
using AQI.Interview.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AQI.Interview.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("AQI.Interview.Models.Measurement", b =>
                {
                    b.Property<long>("MeasurementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double?>("NumericValue")
                        .HasPrecision(18, 6)
                        .HasColumnType("REAL");

                    b.Property<int>("Parameter")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Precision")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StringValue")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UTCCapturedTimestamp")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UTCSavedTimestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("MeasurementId");

                    b.ToTable("Measurements");
                });
#pragma warning restore 612, 618
        }
    }
}
